### ISSUE TITLE
Why did you not use one of the listed alternatives

### ISSUE THREAD

**Issue by guettli** [aranzgeo/properties#160]
First a big thank you for the very well structured documentation at this page: https://pypi.python.org/pypi/properties

Next thank you: You list the alternatives. This way I know that you think before coding.

I am missing one thing: Why did you not use one of the listed alternatives (traits, traitlets, mypy and PEP0484).

**Comment by fwkoch** [comment]
Hi @guettli - Thanks for the kind words!

Regarding your question: First, take a look here for the updated readme: http://propertiespy.readthedocs.io/en/latest/#alternatives - the "Alternatives" section has been significantly expanded with much more explanation _why_. (Unfortunately the readme on PyPI will not be updated until the next code release.)

=============

If you are interested, let me go a bit deeper into our thought process. It really comes down to high-level goals for the library. What we wanted was a library that focused on usability and reproducibility in an interactive computing environment. This means facilitating the creation of classes that are
- documented (this means not only helpful docstrings, but also a clean namespace and declarative, easy-to-follow source code),
- behave for users as the developer prescribes but are flexible enough for interactive use, and
- may be easily serialized/deserialized for transferability both within and beyond the interactive computing domain.

For the alternatives, `mypy`/`PEP0484` have a very different scope. They introduce static typing - great for debugging, maintenance, and enforcing certain behavior with basically no overhead. However, this isn't well suited for interactive computing, and it doesn't meet all our goals. The `param` library and built-in Python `property` are also mentioned in the updated readme - again, they do not meet many of our goals.

`traits` and `traitlets` are the most compelling alternatives (I use these interchangeably since traitlets is [designed to reproduce many of the capabilities of traits](https://github.com/ipython/traitlets/blob/4.3.2/traitlets/traitlets.py#L5)). In fact, we started out using traitlets - it helped us reach some of our goals with validation, notifications, and declarative code. Their [config](https://github.com/ipython/traitlets/tree/4.3.2/traitlets/config) implementation was possibly a step towards the serialization we were looking for. However, at a high-level, the goals differ; traits and traitlets focus on GUI interaction, not usable, reproducible code. As a result, a few conflicts with our goals arose. For example
- Instances cannot exist in an invalid state. This makes sense in the context of constrained GUIs, but it inhibits construction and exploration that come along with interactive use.
- Namespace contains many extra attributes
  <img width="352" alt="screen shot 2017-04-20 at 12 46 50 am" src="https://cloud.githubusercontent.com/assets/9453731/25217148/fc14a54c-2562-11e7-9929-a26e12f6e2ea.png">
  vs
  <img width="330" alt="screen shot 2017-04-20 at 1 24 07 am" src="https://cloud.githubusercontent.com/assets/9453731/25218445/201a2192-2568-11e7-97c2-296b3c0d65c8.png">
- Configuration is treated as a separate, complex layer. Not exactly the smooth, simple serialization/deserialization we were looking for.
- Automatic documentation is not yet implemented, but it is getting developed similar to configuration, ie as another separate, complex layer. It requires extra work that a rapidly prototyping developer probably won't do (therefore these early prototypes will be undocumented and less usable). The traitlets approach allows more flexibility at the cost of complexity, in line with their goals but not ours. (see the discussion here: https://github.com/ipython/traitlets/pull/261 )

To some degree, these issues could be overcome by customizing traitlets to fit our needs. But still, the fundamental, high-level design differences would permeate. We decided it was worth developing our own `properties` library that focused on simple, interactive usability and reproducibility. Of course, we see huge value in traitlets - there is significant inspiration from traitlets in `properties` and #155 allows connecting properties to traitlets (and therefore ipython widgets, etc).
