### ISSUE TITLE
List props returns invalid empty list

### ISSUE THREAD

**Issue by rowanc1** [aranzgeo/properties#169]
When not initialized the list properties return an empty list rather than `None`. This is confusing as in the case below, that is not even a valid thing:

```python
import properties
class Array(properties.HasProperties):
    shape = properties.List(
        'shape of the 2d array',
        prop=properties.Integer('', min=1),
        min_length=2,
        max_length=2,
    )
a = Array()
print(a.shape)
#> []
```

**Comment by rowanc1** [comment]
What is worse is that if the property is also not required, it will fail validation.

**Comment by fwkoch** [comment]
I disagree that the first comment is a bug, it's just the way things are designed (for now...). A container property's `_class_default` value is an empty container, regardless of anything else. Looking through the documentation, though, looks like that's never stated... You can always set `default=properties.undefined`; then `a.shape` is `None`. In this case, though, `a.validate()` will still fail until `shape` is set correctly. Whether or not this is the correct behavior is a different story...

...which brings up your second comment. I agree that is a very bad bug-like consequence that I hadn't thought of (if there is no `min_length` requirement and the list property is unset, `None` vs `[]` shouldn't be a big difference). Anyway, I think this is probably enough reason to change the default behavior.

That has possible implications for existing code that may assume the list is instantiated by default. Needs some investigation before acting.

~Another possibly safer but definitely more complicated solution is making the default undefined if `required=False` but `[]` otherwise... Something to consider, but I really don't like this. Yeah. Really don't like it.~

Anyway, as a temporary fix, just set `default=properties.undefined`. Then things should behave as you expect.

**Comment by fwkoch** [comment]
I guess really it's just a question of taste. Do we require users who _do not_ want an initialized list to set `default=properties.undefined`? or do we require users who _do_ want an initialized list to set `default=list`?

**Comment by fwkoch** [comment]
Another related bug-like thing here with defaults that are not undefined. Given something like this:

```python
    values = properties.Union(
        'Lists of similar type values',
        props=[
            properties.List('', properties.Integer(''), min_length=2),
            properties.List('', properties.Float(''), min_length=2),
            properties.List('', properties.DateTime(''), min_length=2),
        ],
        default=properties.undefined,
    )
```

I'd expect the undefined default to override the list `[]` default. But it does not, the default instead is set to the list default.

This leads a bit into another question - do we want union properties to grab sub-`props`'s defaults? Makes more sense if you look at something like this:

```python
    value = properties.Union(
        'Float, Int, or DateTime',
        props=[
            properties.Integer('', default=5),
            properties.Float(''),
            properties.DateTime(''),
        ],
    )
```
The the default for the union property will be 5 as well. But maybe that isn't what we want either...?

Anyway, definitely need to rethink the empty list default.

**Comment by fwkoch** [comment]
Empty list defaults have been removed with #219 - the backwards incompatibility means the next release is 0.4.0, but this is a necessary change to fix the above behaviour and add some consistency to property defaults
