### ISSUE TITLE
conda-forge

### ISSUE THREAD

**Issue by lheagy** [aranzgeo/properties#179]
We are working on using conda-forge for the distribution of `discretize` (see: simpeg/discretize#69). For this, we need dependencies to also be distributed through conda-forge. Would you be willing to put `properties` (and `vectormath`) on conda-forge?
https://conda-forge.org/docs/recipe.html

**Comment by fwkoch** [comment]
Ok! I'll check it out.

**Comment by fwkoch** [comment]
@lheagy - properties (and vectormath) are now on conda-forge! One minor note - `properties.ImagePNG` isn't supported directly through the conda distribution since `pypng` isn't on conda-forge. A future release of properties should be able to work around this by including the `pypng` code, but I'm _assuming_ this isn't a problem for `discretize`?

Looking forward to seeing discretize, etc find their way to conda-forge.

https://anaconda.org/conda-forge/properties

**Comment by leouieda** [comment]
@fwkoch you can package pypng on conda-forge if you want. There is no restriction on being the original author (though that usually helps).

**Comment by lheagy** [comment]
thank you @fwkoch!
