### ISSUE TITLE
default shape of properties.Array

### ISSUE THREAD

**Issue by lheagy** [aranzgeo/properties#192]
This has also been prompted while working on bringing properties into discretize (simpeg/discretize#70). 

It seems that the default shape for an array is `('*',)`, but I am running into a scenario where I don't know the shape a-priori. If a 1D mesh is set up, the array will be `('*',)` , if it is 2D, then it will be `('*', '*')` and if it is 3D, then it is `('*', '*', '*')`. 

My current trajectory forward is to sub-class `Array` and over-write the shape, but I am also wondering if it is worth allowing a more flexible array type in `properties`. Perhaps something like `shape='*'` is a wild-card and would allow any of the above use cases?

**Comment by lheagy** [comment]
For context, the `nodes` property is the one I am referring to

```python
class CurvilinearMesh(
    BaseRectangularMesh, DiffOperators, InnerProducts, CurviView
):
    _meshType = 'Curv'

    nodes = properties.List(
        "List of arrays describing the node locations",
        properties.Array(
            "node locations in a dimension",
            shape='*'
        ),
    )
```

**Comment by fwkoch** [comment]
Hi @lheagy -

One option for this specific use-case is a `Union` property:

```python
nodes = properties.List(
    'list of arrays describing node locations',
    prop=properties.Union(
        'we do not know the dimensions...',
        props=[
            properties.Array('1D', shape=('*',)),
            properties.Array('2D', shape=('*', '*')),
            properties.Array('3D', shape=('*', '*', '*')),
        ]
    )
)
```

For cases that are even less constrained, I like the idea of having something that just turns off shape validation (`shape='*'` or maybe `shape=None` since `'*'` already has some baggage...). This is particularly important to add, I think, since there is currently no way an array of arbitrary shape can reach custom validators (if that makes sense...). Shape must be checked somehow.

It's certainly possible for things to get even more complicated (eg constraining number of dimensions, length of certain dimensions, etc). An option for that is introducing some sort of shape syntax beyond `'*'`s and ints (eg `shape=('1-3', '?*', '?0-10', 'etc')`, but that really doesn't excite me. More complicated logic is what custom validators are for (of course, this requires getting beyond the default array validation, hence the previous paragraph).

**Comment by fwkoch** [comment]
Sets for shape is also interesting. Something like `shape={(1,), (2,), (3,)}`. Basically as shorthand to make a union property... See https://github.com/simpeg/discretize/pull/70/files#r136703484

**Comment by fwkoch** [comment]
See #195

**Comment by fwkoch** [comment]
These features are supported in `properties>=0.3.6b0`
