### ISSUE TITLE
regex variable defined as string treated as a compiled regex

### ISSUE THREAD

**Issue by riscy** [aranzgeo/properties#200]
@bsmithyman @fwkoch 

```python
import properties

class TestUID(properties.String):
    class_info = 'a child of properties.String'
    regex = 'abc'

class TestResource(properties.HasProperties):
    uid = TestUID('id of the resource')

resource = TestResource()
resource.uid = 'abc'
```

The code above throws an exception.  I believe the variable `regex` above is allowed to be a string, but it's treated as a regex in the [`validate` method](https://github.com/aranzgeo/properties/blob/master/properties/basic.py#L971).

**Comment by fwkoch** [comment]
Thanks, @riscy - The reason `validate` assumes this is compiled is because in the setter coerces strings to compiled regex - see here: https://github.com/aranzgeo/properties/blob/v0.3.5/properties/basic.py#L962 - The way you define `TestUID`, however, overrides the `@property` `regex` with just a string (so the setter is no longer called).

Currently, you can replicate the above class in a way that calls the setter with something like:

```python
import properties

class TestUID(properties.String):
    class_info = '...'

    def __init__(self, *args, **kwargs):
        kwargs.update({'regex': 'abc'})
        return super(TestUID, self).__init__(*args, **kwargs)
```

However, it would be nice to define a class as you do above. This has implications beyond `regex` though. You could override any attribute (well, `@property`) in a `properties.Property` class this way. That would mean moving all setter validation to somewhere it can be run if the `@property` is overridden - eg on class construction or inside `validate`...

**Comment by riscy** [comment]
I see!  Thanks for the explanation and the solution.
