### ISSUE TITLE
minimum value for an Array Property? 

### ISSUE THREAD

**Issue by lheagy** [aranzgeo/properties#216]
There are a few cases where having a `min` (or `max`) would be helpful for an array. For example, I am building an array property of uncertainties, and all entries should be positive.

**Comment by fwkoch** [comment]
Hey @lheagy - I see where you are coming from but I'm hesitant to add these to the built-in `properties.Array`. Since `bool` and `complex` are now valid `dtype`s, `min` and `max` don't always make sense, so introducing them adds some baggage.

This is pretty easy for you to add yourself though. You have a couple options. If you are only need a positive array in one or two places, you can add a `properties.validator` on the class:

```python
import numpy as np
import properties

class HasPositiveArray(properties.HasProperties):
    
    my_arr = properties.Array('My array with entries > 0')
    
    @properties.validator('my_arr')
    def _assert_positive(self, change):
        if np.any(change['value'] < 0):
            raise ValueError('my_arr must be > 0')
```

If you need this positive array everywhere, you can make your own custom `PositiveArray` property class where you override validate:

```python
import numpy as np
import properties

class PositiveArray(properties.Array):
    
    def validate(self, instance, value):
        value = super(PositiveArray, self).validate(instance, value)
        if np.any(value < 0):
            raise ValueError('my_arr must be > 0')
        return value

class HasPositiveArray(properties.HasProperties):
    
    my_arr = PositiveArray('My array with entries > 0')
```

Both of these should give you the results you are looking for:
![image](https://user-images.githubusercontent.com/9453731/36333398-ea5d9d1c-1333-11e8-97c0-e795fd77b6a6.png)

Let me know if you have any more questions!

**Comment by lheagy** [comment]
Thanks @fwkoch!
