### ISSUE TITLE
Write Once Property

### ISSUE THREAD

**Issue by rowanc1** [aranzgeo/properties#23]
Ability to have a write once property.

**Comment by fwkoch** [comment]
Right now the closest to this is `GettableProperty`. This can have a default value (possibly a callable) that is set on instantiation and unchanged after that.

This is slightly different than a property that can be written once by the user.

**Comment by bsmithyman** [comment]
Sounds interesting. What's the use case?

**Comment by fwkoch** [comment]
This is similar to a `GettableProperty` with a dynamically created default value. For example, here `UidModel` has `date_created`, an immutable property set on construction: https://github.com/aranzgeo/omf/blob/v0.9.0/omf/base.py#L21

Write once property would be for something similar, where the value on construction would need to be provided by the user, rather than set to a programatic default. However, I haven't yet encountered a use-case for that, which is why this is still a pending issue.

**Comment by fwkoch** [comment]
I'm inclined to close this since no valid use case has come up. The closest thing is something like an api key that is generated once, displayed to the user, then inaccessible after that. However, I don't think something like that is within the scope of `properties`.
